/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualTourRouteImport } from './routes/virtual-tour'
import { Route as KnockDownRebuildRouteImport } from './routes/knock-down-rebuild'
import { Route as HomeDesignsRouteImport } from './routes/home-designs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DisplayHomesRouteImport } from './routes/display-homes'
import { Route as DevelopmentsRouteImport } from './routes/developments'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const VirtualTourRoute = VirtualTourRouteImport.update({
  id: '/virtual-tour',
  path: '/virtual-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const KnockDownRebuildRoute = KnockDownRebuildRouteImport.update({
  id: '/knock-down-rebuild',
  path: '/knock-down-rebuild',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDesignsRoute = HomeDesignsRouteImport.update({
  id: '/home-designs',
  path: '/home-designs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayHomesRoute = DisplayHomesRouteImport.update({
  id: '/display-homes',
  path: '/display-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsRoute = DevelopmentsRouteImport.update({
  id: '/developments',
  path: '/developments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/developments': typeof DevelopmentsRoute
  '/display-homes': typeof DisplayHomesRoute
  '/gallery': typeof GalleryRoute
  '/home-designs': typeof HomeDesignsRoute
  '/knock-down-rebuild': typeof KnockDownRebuildRoute
  '/virtual-tour': typeof VirtualTourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/developments': typeof DevelopmentsRoute
  '/display-homes': typeof DisplayHomesRoute
  '/gallery': typeof GalleryRoute
  '/home-designs': typeof HomeDesignsRoute
  '/knock-down-rebuild': typeof KnockDownRebuildRoute
  '/virtual-tour': typeof VirtualTourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/developments': typeof DevelopmentsRoute
  '/display-homes': typeof DisplayHomesRoute
  '/gallery': typeof GalleryRoute
  '/home-designs': typeof HomeDesignsRoute
  '/knock-down-rebuild': typeof KnockDownRebuildRoute
  '/virtual-tour': typeof VirtualTourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/developments'
    | '/display-homes'
    | '/gallery'
    | '/home-designs'
    | '/knock-down-rebuild'
    | '/virtual-tour'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/developments'
    | '/display-homes'
    | '/gallery'
    | '/home-designs'
    | '/knock-down-rebuild'
    | '/virtual-tour'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/developments'
    | '/display-homes'
    | '/gallery'
    | '/home-designs'
    | '/knock-down-rebuild'
    | '/virtual-tour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  DevelopmentsRoute: typeof DevelopmentsRoute
  DisplayHomesRoute: typeof DisplayHomesRoute
  GalleryRoute: typeof GalleryRoute
  HomeDesignsRoute: typeof HomeDesignsRoute
  KnockDownRebuildRoute: typeof KnockDownRebuildRoute
  VirtualTourRoute: typeof VirtualTourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-tour': {
      id: '/virtual-tour'
      path: '/virtual-tour'
      fullPath: '/virtual-tour'
      preLoaderRoute: typeof VirtualTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knock-down-rebuild': {
      id: '/knock-down-rebuild'
      path: '/knock-down-rebuild'
      fullPath: '/knock-down-rebuild'
      preLoaderRoute: typeof KnockDownRebuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-designs': {
      id: '/home-designs'
      path: '/home-designs'
      fullPath: '/home-designs'
      preLoaderRoute: typeof HomeDesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display-homes': {
      id: '/display-homes'
      path: '/display-homes'
      fullPath: '/display-homes'
      preLoaderRoute: typeof DisplayHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments': {
      id: '/developments'
      path: '/developments'
      fullPath: '/developments'
      preLoaderRoute: typeof DevelopmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  DevelopmentsRoute: DevelopmentsRoute,
  DisplayHomesRoute: DisplayHomesRoute,
  GalleryRoute: GalleryRoute,
  HomeDesignsRoute: HomeDesignsRoute,
  KnockDownRebuildRoute: KnockDownRebuildRoute,
  VirtualTourRoute: VirtualTourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
